Extract the models from the script, liven it up a bit.
Arrex3/Animal-Fight-Club pull request #1
Opened 2022-10-01 20:36 UTC by perrygoy

This PR splits up the original Animal Fight Club script into smaller, more focused files. This step will hopefully set us up for success as we add more features to Animal Fight Club.

Firstly, the models now live in `/models/*.py`. I added a base `Fighter` class which `Animal` inherits from, and a `Referee` class which runs the fights and does some fun announcements.

Secondly, i made it so any number of fighters can enter the fight, and made our roster randomized. Here's an example run:

```
We've got a great fight for you today folks, just look at these 9 fighters...
In the left-middle corner, still wearing their bathrobe, UNICORN!
And in the right corner, with a face only their mother could love, BASILISK!
And in the right corner, brushing their teeth with steel wool, WOLVERINE!
And in the kitty corner, building a card tower, KOMODO DRAGON!
And in the left-middle corner, with rage in their eyes, DUCK!
And in the top-left corner, texting their buddies back home, MOUSE!
And in the right-middle corner, all the way from Saskatoon, STUART!
And in the far corner, with rage in their eyes, NEWT!
And in the right corner, building a card tower, ELEPHANT!
Let's get READY TO RUMBLE!!!

All right everyone, i want a good clean fight. First to 100!

newt wins!
newt: ROAR!!!
```

2022-10-03 02:23 UTC, Arrex3 requested changes

2022-10-03 02:23 UTC, Arrex3 commented on models/referee.py
> +]
I would prefer to have these in their own files

2022-10-03 02:23 UTC, Arrex3 commented on models/referee.py
> +    def fight(self, to: int = 100) -> Fighter:
"fight" should be "ref_round"

2022-10-03 02:23 UTC, Arrex3 commented on animal_fight_club.py
> +]
These should go in the same data file

2022-10-03 18:57 UTC, perrygoy commented on models/referee.py
> +    def fight(self, to: int = 100) -> Fighter:
I changed it to `run_tournament` after looking up some definitions and stuff. How's that sound?

2022-10-03 18:57 UTC, perrygoy commented on animal_fight_club.py
> +]
✅

2022-10-04 02:37 UTC, Arrex3 approved these changes

2022-10-04 02:37 UTC, merged